# Site Specific Configuration
name: 월리의 탐구생활
description: 개발자라면 하나쯤은 있을법한 블로그
url: https://wnjoon.github.io
author: wonjoon
timezone: Asia/Seoul
timezone_short: KR

# Keywords
keywords: ['seo', 'key', 'words']

# Analytics (Plausible requires sign-up)
analytics:
  plausible:
    enabled: false
    site_fqdn: 'your.site.fqdn'
    script_source: 'https://plausible.io/js/script.js'

# Permalink
# permalink: /:year/:month/:day/:title

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Paginate
pagination:
  enabled: true
  # Value set low for demonstration purposes
  per_page: 10
  sort_field: 'date'
  sort_reverse: true

# Category Paginating
autopages:
  enabled: true
  categories:
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    silent: false
  posts:
    

# Exclusions
exclude: [ 'README.md', 'COPYING' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag


