title: "blog.wonjoon" # name of the site
author: Wonjoon # name of site's author
email: wnjoon@gmail.com # email of site's author
url: https://wnjoon.github.io # root address of the site
# baseurl: "/bundle" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  A blog about software engineering, blockchain, and other development topics.

# permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# theme: no-style-please
# remote_theme: riggraz/no-style-please 

theme_config:
  appearance: "white" # can be "light", "dark" or "auto"
  back_home_text: "<-home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

permalink: /:year/:month/:day/:title/

sass:
  style: "expanded"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag